# This file was generated by GoReleaser. DO NOT EDIT.
cask "encomplayer" do
  version "1.7.1"

  on_macos do
    on_arm do
      sha256 "7c2293812f32d6b035d53122885ba88b82f065d5a7df7fbfdfe86fbbf1214c21"
      url "https://github.com/matjam/encomplayer/releases/download/v#{version}/encomplayer_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "291a9b98ad31211542ab6211d0b7176b17581734fc57d328ed1ed3c2c161338f"
      url "https://github.com/matjam/encomplayer/releases/download/v#{version}/encomplayer_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "50c65272e52fcb6c57a52513db6caa67baa8d9a81217e083a2acfb42e7e53e65"
      url "https://github.com/matjam/encomplayer/releases/download/v#{version}/encomplayer_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "dd526ab2f5b97aa73a129f7699ca7cf5ec01472664923e06f14a0b870b14e3c0"
      url "https://github.com/matjam/encomplayer/releases/download/v#{version}/encomplayer_#{version}_linux_amd64.tar.gz"
    end
  end

  name "encomplayer"
  desc "Terminal music player styled after ENCOM OS-12, with rmpc keybindings"
  homepage "https://github.com/matjam/encomplayer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "encomplayer"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/encomplayer"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    MP3, FLAC, Ogg Vorbis and WAV play out of the box. For AAC/M4A, ALAC,
    Opus, WavPack and other formats, install ffmpeg:
      brew install ffmpeg
  EOS
end
