# This file was generated by GoReleaser. DO NOT EDIT.
cask "encomplayer" do
  version "1.2.0"

  on_macos do
    on_arm do
      sha256 "d08c544cbb63eb555610db8aeb0fd7b8158176a4ecd942ed20664fe0ee98eb7a"
      url "https://github.com/matjam/encomplayer/releases/download/v#{version}/encomplayer_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7441a90c32630879bc85780e7f1f05b45e522a546367cc9e102a5ed45720850b"
      url "https://github.com/matjam/encomplayer/releases/download/v#{version}/encomplayer_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2115ad4d8237de99ff0e23d1e35027256849145a9bc32bcf75d4a12e55eb1c70"
      url "https://github.com/matjam/encomplayer/releases/download/v#{version}/encomplayer_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2ca2fc9dce1e9a4552416e9b4bebb2cdbec903dd7a6bc22e9fc22a140e3f16d3"
      url "https://github.com/matjam/encomplayer/releases/download/v#{version}/encomplayer_#{version}_linux_amd64.tar.gz"
    end
  end

  name "encomplayer"
  desc "Terminal music player styled after ENCOM OS-12, with rmpc keybindings"
  homepage "https://github.com/matjam/encomplayer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "encomplayer"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/encomplayer"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    MP3, FLAC, Ogg Vorbis and WAV play out of the box. For AAC/M4A, ALAC,
    Opus, WavPack and other formats, install ffmpeg:
      brew install ffmpeg
  EOS
end
