# This file was generated by GoReleaser. DO NOT EDIT.
cask "encomplayer" do
  version "1.6.0"

  on_macos do
    on_arm do
      sha256 "7e4c593561863a6d174454b94f4e77b111368b3cffb66c95faff3d453762b4fe"
      url "https://github.com/matjam/encomplayer/releases/download/v#{version}/encomplayer_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "324409633a0b29946cede7f317787ee04caba77764bbcdd665bd3478df78ad5e"
      url "https://github.com/matjam/encomplayer/releases/download/v#{version}/encomplayer_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ee2b7cc62bfc5d8740cc60e2c687fcc0259ff16765bf77b82f36731d7289b65d"
      url "https://github.com/matjam/encomplayer/releases/download/v#{version}/encomplayer_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b7b28dcbe1ab742e5c1e240d971a14eb7a6961d329190ca1016a533122369abc"
      url "https://github.com/matjam/encomplayer/releases/download/v#{version}/encomplayer_#{version}_linux_amd64.tar.gz"
    end
  end

  name "encomplayer"
  desc "Terminal music player styled after ENCOM OS-12, with rmpc keybindings"
  homepage "https://github.com/matjam/encomplayer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "encomplayer"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/encomplayer"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    MP3, FLAC, Ogg Vorbis and WAV play out of the box. For AAC/M4A, ALAC,
    Opus, WavPack and other formats, install ffmpeg:
      brew install ffmpeg
  EOS
end
